#端口
server: 
  port: 8080
  tomcat: 
    uri-encoding: UTF-8
spring:
  thymeleaf:
      prefix: classpath:/templates
      encoding: UTF-8
  #缓存
      cache: false
#表示所有的访问都经过静态资源路径；
  mvc:
    static-path-pattern: /**
#在这里配置静态资源路径，前面说了这里的配置是覆盖默认配置，
#所以需要将默认的也加上否则static、public等这些路径将不能被当作静态资源路径，
#在这个最末尾的file:${web.upload-path}之所有要加file:是因为指定的是一个具体的硬盘路径，
#其他的使用classpath指的是系统环境变量
  resources:
    static-locations: classpath:/static/,classpath:/public/,file:${imgPath}

# 日志级别
#debug: true
#info: true
error: true
#输出到log文件
logging:
    file: docx.log

#分页每页默认条数设置
page:
  pageSize: 5

files:
#model路径
  m: D:\model.docx
#完整版路径
  w: D:\w\
#精简版路径
  j: D:\j\
